# This Dockerfile builds the React front end for nginx.
# It also proxies /api requests to api:5000

# Build step #1: build the Vite/Lovable front end
FROM node:20-alpine AS build-step
WORKDIR /app/src
COPY src/package.json src/package-lock.json ./
RUN npm ci
COPY src/ ./
RUN npm run build

# Build step #2: build an nginx container
FROM nginx:stable-alpine
COPY --from=build-step /app/build/client /usr/share/nginx/html
COPY deployment/nginx.default.conf /etc/nginx/conf.d/default.conf
