/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentPersonalityRouteImport } from './routes/agent.personality'
import { Route as AgentFamilyRouteImport } from './routes/agent.family'
import { Route as AgentCourseRouteImport } from './routes/agent.course'
import { Route as AgentCoordinatorRouteImport } from './routes/agent.coordinator'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentPersonalityRoute = AgentPersonalityRouteImport.update({
  id: '/agent/personality',
  path: '/agent/personality',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentFamilyRoute = AgentFamilyRouteImport.update({
  id: '/agent/family',
  path: '/agent/family',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentCourseRoute = AgentCourseRouteImport.update({
  id: '/agent/course',
  path: '/agent/course',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentCoordinatorRoute = AgentCoordinatorRouteImport.update({
  id: '/agent/coordinator',
  path: '/agent/coordinator',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/agent/coordinator': typeof AgentCoordinatorRoute
  '/agent/course': typeof AgentCourseRoute
  '/agent/family': typeof AgentFamilyRoute
  '/agent/personality': typeof AgentPersonalityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/agent/coordinator': typeof AgentCoordinatorRoute
  '/agent/course': typeof AgentCourseRoute
  '/agent/family': typeof AgentFamilyRoute
  '/agent/personality': typeof AgentPersonalityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/agent/coordinator': typeof AgentCoordinatorRoute
  '/agent/course': typeof AgentCourseRoute
  '/agent/family': typeof AgentFamilyRoute
  '/agent/personality': typeof AgentPersonalityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/agent/coordinator'
    | '/agent/course'
    | '/agent/family'
    | '/agent/personality'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/agent/coordinator'
    | '/agent/course'
    | '/agent/family'
    | '/agent/personality'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/agent/coordinator'
    | '/agent/course'
    | '/agent/family'
    | '/agent/personality'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  AgentCoordinatorRoute: typeof AgentCoordinatorRoute
  AgentCourseRoute: typeof AgentCourseRoute
  AgentFamilyRoute: typeof AgentFamilyRoute
  AgentPersonalityRoute: typeof AgentPersonalityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/personality': {
      id: '/agent/personality'
      path: '/agent/personality'
      fullPath: '/agent/personality'
      preLoaderRoute: typeof AgentPersonalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/family': {
      id: '/agent/family'
      path: '/agent/family'
      fullPath: '/agent/family'
      preLoaderRoute: typeof AgentFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/course': {
      id: '/agent/course'
      path: '/agent/course'
      fullPath: '/agent/course'
      preLoaderRoute: typeof AgentCourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/coordinator': {
      id: '/agent/coordinator'
      path: '/agent/coordinator'
      fullPath: '/agent/coordinator'
      preLoaderRoute: typeof AgentCoordinatorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  AgentCoordinatorRoute: AgentCoordinatorRoute,
  AgentCourseRoute: AgentCourseRoute,
  AgentFamilyRoute: AgentFamilyRoute,
  AgentPersonalityRoute: AgentPersonalityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
